name: Terraform Plan

on:
  pull_request:
    branches: [ main ]

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: "1.3.0"

      - name: Terraform Init
        run: |
          cd terraform/environments/test
          terraform init

      - name: Terraform Plan
        run: |
          cd terraform/environments/test
          terraform plan -out=tfplan
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

      - name: Run tflint
        uses: terraform-linters/setup-tflint@v2
        with:
          tflint_version: v0.45.0

      - name: Run tflint
        run: |
          cd terraform
          tflint --init
          tflint 